### PR TITLE
Migration to the new .csproj format.

### PR DESCRIPTION
**Pull request by Federerer**

### CODE REVIEW

**Review by dsharlet — COMMENTED** [review]
Thanks, this looks pretty good. Were you planning to make other changes (given it is marked as a draft)?

I assume the plotting changes were necessary to avoid dependencies?

**Comment by Federerer** [comment]
I've marked this as a draft, because I want to test this when I finish LiveSpice migration.
Plotting has been moved to avoid dragging in windows forms to the cross platform library :)

**Comment by dsharlet** [comment]
OK, that makes sense. We'll merge both of the PRs at the same time.

**Comment by dsharlet** [comment]
I just merged the LiveSPICE version of this, going to merge this. Thanks for doing this!

**Pull request merged**
